### ISSUE TITLE
Some improvements for the about section

### ISSUE THREAD

**Issue by N3tt3rm4n** [muonium/website#3]
My feedback about what's missing:
- [ ] Add link to GitHub
- [ ] Add tooltips to LinkedIn and GitHub images (-> title attribute)
- [ ] Maybe Facebook, Twitter etc. if availible

![auswahl_001](https://cloud.githubusercontent.com/assets/25689289/24654920/30a0d2b4-193c-11e7-878c-44db624ec07f.png)

What d'you think?

**Comment by Super-Baleine** [comment]
Hey,
Yea, we'll do that, that's planned, thanks anyway x)
